'use client';

import Link from 'next/link';
import { FormEvent, useState } from 'react';
import { useNotification } from '@/components/notification';

export function PasswordResetForm({ mode, token = '' }: { mode: 'request' | 'confirm'; token?: string }) {
  const { notify } = useNotification(); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [complete, setComplete] = useState(false); const [submitting, setSubmitting] = useState(false);
  const submit = async (event: FormEvent) => { event.preventDefault(); setSubmitting(true); try { const endpoint = mode === 'request' ? '/api/auth/password-reset/request' : '/api/auth/password-reset/confirm'; const response = await fetch(endpoint, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(mode === 'request' ? { email } : { token, password }) }); const body = await response.json() as { message?: string; error?: string }; if (!response.ok) throw new Error(body.error ?? 'Unable to reset password.'); setComplete(true); notify('success', mode === 'request' ? 'If your account exists, a reset email has been sent.' : 'Password updated. You can now sign in.'); } catch (error) { notify('failure', error instanceof Error ? error.message : 'Unable to reset password.'); } finally { setSubmitting(false); } };
  const title = mode === 'request' ? 'Reset your password' : 'Choose a new password';
  return <main className="grid min-h-screen place-items-center bg-slate-50 px-4 py-10"><section className="w-full max-w-md rounded-2xl border border-slate-200 bg-white p-6 shadow-xl shadow-slate-200/50 sm:p-8"><h1 className="text-2xl font-bold text-slate-900">{title}</h1><p className="mt-2 text-sm leading-6 text-slate-600">{mode === 'request' ? 'Enter your account email and we will send a secure reset link.' : 'Use a password with at least 12 characters.'}</p>{complete ? <p className="mt-6 text-sm text-slate-700">{mode === 'request' ? 'Check your inbox for the reset link. It expires in one hour.' : 'Your password has been updated.'}</p> : <form className="mt-6 space-y-4" onSubmit={(event) => void submit(event)}>{mode === 'request' ? <label className="block text-sm font-medium text-slate-700">Email<input autoComplete="email" type="email" value={email} onChange={(event) => setEmail(event.target.value)} required className="mt-1.5 w-full rounded-lg border border-slate-300 px-3 py-2.5" /></label> : <label className="block text-sm font-medium text-slate-700">New password<input autoComplete="new-password" type="password" minLength={12} value={password} onChange={(event) => setPassword(event.target.value)} required className="mt-1.5 w-full rounded-lg border border-slate-300 px-3 py-2.5" /></label>}<button disabled={submitting || (mode === 'confirm' && !token)} className="w-full rounded-lg bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-60">{submitting ? 'Please wait…' : mode === 'request' ? 'Send reset link' : 'Update password'}</button></form>}<p className="mt-6 text-center text-sm text-slate-600"><Link href="/login" className="font-semibold text-blue-700">Return to sign in</Link></p></section></main>;
}
